baseURL: https://kerthcet.com/ # Replace with your domain
languageCode: en-us
theme: smigle
themesDir: ../.. # Only needed for running the example site
title: Hi, I'm Kante Yin üëã
menu:
  main: # Change menu as needed
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About Me
      url: /about-me/
      weight: 2
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 3
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 4
    - identifier: moments
      name: Moments
      url: /moments/
      weight: 5
    - identifier: talks
      name: Talks
      url: /talks/
      weight: 6
    - identifier: awards
      name: Awards
      url: /awards/
      weight: 7
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 7
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 8
params:
  abbrDateFmt: "Jan 2"
  author: "kerthcet"
  brandIconFile: "images/kerthcet.png"
  dateFmt: "2006-01-02"
  ##
  ## Options for overriding theme or page defaults
  ##
  customStylesheets: # Use to override theme styles, like logo size
    - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range
  social:
    - name: GitHub
      url: https://github.com/kerthcet
    - name: X
      url: https://x.com/kerthcet
    - name: Bluesky
      url: https://kerthcet.bsky.social/
    - name: LinkedIn
      url: https://www.linkedin.com/in/kerthcet/
    - name: WeChat
      url: https://raw.githubusercontent.com/kerthcet/kerthcet/main/snapshots/wechat.jpg
  subtitle: "R&D Engineer ‚Ä¢ OpenSource Enthusiast ‚Ä¢ Cat Owner ‚Ä¢ Sports Fan ‚öΩÔ∏è üèÄ ü•ä"
pagination:
  pagerSize: 10
mainSections: ["posts", "moments", "talks", "awards"]
summaryLength: 15
